### ISSUE TITLE
Orchestrate Data Lake stack (Apache Kafka cluster) containers in Kubernetes

### ISSUE THREAD

**Issue by JohnSundarrajJSR** [sloopstash/kickstart-kubernetes#15]
### Workload containers
- [x] Kubernetes YAML

**Comment by DivyaPriya-Muthuvel** [comment]
- Improved Kubernetes components to work seamlessly in a multi-environment setup suitable for on-premise deployments.
- Enhanced persistent volume templates to map with the corresponding persistent volume claims.
- Updated stateful-set files for broker and controller nodes, incorporating key-value pairs for config maps.

**Comment by JohnSundarrajJSR** [comment]
@DivyaPriya-Muthuvel its good to see valid explaination about the tasks. Thank you.
