### ISSUE TITLE
Orchestrate Data Lake stack (Apache Hadoop cluster) containers in Kubernetes

### ISSUE THREAD

**Issue by JohnSundarrajJSR** [sloopstash/kickstart-kubernetes#16]
### Workload containers
- [x] Kubernetes YAML

**Comment by DivyaPriya-Muthuvel** [comment]
- Improved Kubernetes components to work seamlessly in a multi-environment setup suitable for on-premise deployments.
- Enhanced persistent volume templates to map with the corresponding persistent volume claims.
- Updated stateful-set files for data and name nodes, incorporating key-value pairs for config maps.
