### ISSUE TITLE
Add support for HA master nodes in Kubernetes cluster

### ISSUE THREAD

**Issue by kirankumar023** [sloopstash/kickstart-kubernetes#2]
Hi @sloopstash/devops , We have been using your Kubernetes starter-kit for our organization's purpose. It s good so far, but we also want a support for adding multiple master nodes in the K8s cluster. It would be great if master HA support is added to starter-kit. 

Thank you.

**Comment by sathiyaraj-sridhar** [comment]
Sure @kirankumar023 , we'll take your issue as an enhancement and we'll resolve this issue asap. Thank you.

**Comment by JohnSundarraj** [comment]
@kirankumar023 the issues now resolved.
